const StatusActionTypes = {
    STATUS_LIST_REQUEST: 'STATUS_LIST_REQUEST',
    STATUS_LIST_SUCCESS: 'STATUS_LIST_SUCCESS',
    STATUS_LIST_FAIL: 'STATUS_LIST_FAIL',
    STATUS_DETAILS_REQUEST: 'STATUS_DETAILS_REQUEST',
    STATUS_DETAILS_SUCCESS: 'STATUS_DETAILS_SUCCESS',
    STATUS_DETAILS_FAIL: 'STATUS_DETAILS_FAIL',
    STATUS_DELETE_REQUEST: 'STATUS_DELETE_REQUEST',
    STATUS_DELETE_SUCCESS: 'STATUS_DELETE_SUCCESS',
    STATUS_DELETE_FAIL: 'STATUS_DELETE_FAIL',    
    STATUS_CREATE_REQUEST: 'STATUS_CREATE_REQUEST',
    STATUS_CREATE_SUCCESS: 'STATUS_CREATE_SUCCESS',
    STATUS_CREATE_FAIL: 'STATUS_CREATE_FAIL',
    STATUS_CREATE_RESET: 'STATUS_CREATE_RESET',
    STATUS_UPDATE_REQUEST: 'STATUS_UPDATE_REQUEST',
    STATUS_UPDATE_SUCCESS: 'STATUS_UPDATE_SUCCESS',
    STATUS_UPDATE_FAIL: 'STATUS_UPDATE_FAIL',
    STATUS_UPDATE_RESET: 'STATUS_UPDATE_RESET'
};

export default StatusActionTypes;