const ReactionActionTypes = {
    REACTION_LIST_REQUEST: 'REACTION_LIST_REQUEST',
    REACTION_LIST_SUCCESS: 'REACTION_LIST_SUCCESS',
    REACTION_LIST_FAIL: 'REACTION_LIST_FAIL',
    REACTION_DETAILS_REQUEST: 'REACTION_DETAILS_REQUEST',
    REACTION_DETAILS_SUCCESS: 'REACTION_DETAILS_SUCCESS',
    REACTION_DETAILS_FAIL: 'REACTION_DETAILS_FAIL',
    REACTION_DELETE_REQUEST: 'REACTION_DELETE_REQUEST',
    REACTION_DELETE_SUCCESS: 'REACTION_DELETE_SUCCESS',
    REACTION_DELETE_FAIL: 'REACTION_DELETE_FAIL',    
    REACTION_CREATE_REQUEST: 'REACTION_CREATE_REQUEST',
    REACTION_CREATE_SUCCESS: 'REACTION_CREATE_SUCCESS',
    REACTION_CREATE_FAIL: 'REACTION_CREATE_FAIL',
    REACTION_CREATE_RESET: 'REACTION_CREATE_RESET',
    REACTION_UPDATE_REQUEST: 'REACTION_UPDATE_REQUEST',
    REACTION_UPDATE_SUCCESS: 'REACTION_UPDATE_SUCCESS',
    REACTION_UPDATE_FAIL: 'REACTION_UPDATE_FAIL',
    REACTION_UPDATE_RESET: 'REACTION_UPDATE_RESET'
};

export default ReactionActionTypes;