const CommentActionTypes = {
    COMMENT_LIST_REQUEST: 'COMMENT_LIST_REQUEST',
    COMMENT_LIST_SUCCESS: 'COMMENT_LIST_SUCCESS',
    COMMENT_LIST_FAIL: 'COMMENT_LIST_FAIL',
    COMMENT_DETAILS_REQUEST: 'COMMENT_DETAILS_REQUEST',
    COMMENT_DETAILS_SUCCESS: 'COMMENT_DETAILS_SUCCESS',
    COMMENT_DETAILS_FAIL: 'COMMENT_DETAILS_FAIL',
    COMMENT_DELETE_REQUEST: 'COMMENT_DELETE_REQUEST',
    COMMENT_DELETE_SUCCESS: 'COMMENT_DELETE_SUCCESS',
    COMMENT_DELETE_FAIL: 'COMMENT_DELETE_FAIL',    
    COMMENT_CREATE_REQUEST: 'COMMENT_CREATE_REQUEST',
    COMMENT_CREATE_SUCCESS: 'COMMENT_CREATE_SUCCESS',
    COMMENT_CREATE_FAIL: 'COMMENT_CREATE_FAIL',
    COMMENT_CREATE_RESET: 'COMMENT_CREATE_RESET',
    COMMENT_UPDATE_REQUEST: 'COMMENT_UPDATE_REQUEST',
    COMMENT_UPDATE_SUCCESS: 'COMMENT_UPDATE_SUCCESS',
    COMMENT_UPDATE_FAIL: 'COMMENT_UPDATE_FAIL',
    COMMENT_UPDATE_RESET: 'COMMENT_UPDATE_RESET'
};

export default CommentActionTypes;